apiVersion: v1
kind: Pod
metadata:
  name: "{{ include "cosmocloud-deploy.fullname" . }}-test-connection"
  labels:
    {{- include "cosmocloud-deploy.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  containers:
    - name: wget-backend
      image: busybox
      command: ['wget']
      args: ['http://backend-svc:8000']
    - name: wget-frontend
      image: busybox
      command: ['wget']
      args: ['http://frontend-svc:5175']
    - name: wget-redis
      image: busybox
      command: ['wget']
      args: ['redis://redis-svc:6379']
  restartPolicy: Never
